version: '3.8'

services:
  app:
    image: melqui/mb-challenge.
    volumes:
      - .:/app/src
    networks:
      - fastapi_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
