name: Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry install --no-dev

    - name: Get secrets
      id: secrets
      uses: aws-actions/secrets-manager-get-secret-value@v1
      with:
        aws-region: us-east-1
        secret-id: challenge-mb

    - name: Check PEM
      run: |
        echo "${{ steps.secrets.outputs.SecretString }}"

    - name: Create deployment package
      run: |
        zip -r deployment.zip .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ steps.secrets.outputs.SecretString }}
        script: |
          /home/ubuntu/mb-challenge
          unzip -o ~/deployment.zip